### ISSUE TITLE
Edit HTML pages to retire the "query" end-point

### ISSUE THREAD

**Issue by agstephens** [cedadev/ipcc_ddc_cgi#10]
Edit HTML pages to retire the "query" end-point - can just replace with a "mailto" option for making contact.

**Comment by martinjuckes** [comment]
Can present a subject:
`<a href="mailto:no-one@snai1mai1.com?subject=free chocolate">example</a>` and body: `<a href="mailto:no-one@snai1mai1.com?subject=look at this website&body=Hi,I found this website and thought you might like it http://www.geocities.com/wowhtml/">tell a friend</a>' (see https://stackoverflow.com/questions/4782068/can-i-set-subject-content-of-email-using-mailto).

The CGI `query` script is called from 2 pages: `guidelines/index.md`, `ddc/ddc_visualisation.md`.

There is one mailto link to `support@ceda.ac.uk` on `ddc_help.md`.

**Comment by martinjuckes** [comment]
The `ddc_visualisation` page is an  orphan, now retired.

**Comment by martinjuckes** [comment]
The input markdown pages are fixed, but there are also some legacy HTML pages, under `syn/tar_scatter/scatter_2050_galleries/` which still need to be dealt with.

Also need to remove `ddc_visualisation` from the server (it is cleared from the repo).

**Comment by martinjuckes** [comment]
All links to query removed.

Cleaning `*.md` files to new issue.
